export const mockLeads = [
  {
    id: "1",
    name: "John Doe",
    company: "SolarTech Inc.",
    email: "john.doe@solartech.com",
    website: "www.solartech.com",
    phone: "+34 912 345 678",
    position: "CEO",
    location: "Madrid, España",
    industry: "Solar Installation",
    employees: "50-100",
    revenue: "€2M-5M",
    source: "www.solarinstallers.com",
    confidence: 95,
    lastActivity: "2024-01-26T10:30:00Z",
    notes: "Empresa líder en instalaciones solares residenciales",
    hasWebsite: true,
    websiteExists: true,
    emailValidated: true,
  },
  {
    id: "2",
    name: "Jane Smith",
    company: "Green Energy Co.",
    email: "jane.smith@greenenergyco.net",
    website: "www.greenenergyco.net",
    phone: "+34 913 456 789",
    position: "Director of Operations",
    location: "Barcelona, España",
    industry: "Renewable Energy",
    employees: "100-250",
    revenue: "€5M-10M",
    source: "www.greenenergyfirms.net",
    confidence: 88,
    lastActivity: "2024-01-25T15:45:00Z",
    notes: "Especializada en proyectos comerciales de gran escala",
    hasWebsite: true,
    websiteExists: true,
    emailValidated: true,
  },
  {
    id: "3",
    name: "Robert Johnson",
    company: "EcoSolutions",
    email: "robert@ecosolutions.org",
    website: "www.ecosolutions.org",
    phone: "+34 914 567 890",
    position: "Sustainability Manager",
    location: "Valencia, España",
    industry: "Environmental Consulting",
    employees: "25-50",
    revenue: "€1M-2M",
    source: "www.eco-consultants.org",
    confidence: 92,
    lastActivity: "2024-01-24T09:15:00Z",
    notes: "Consultoría especializada en eficiencia energética",
    hasWebsite: true,
    websiteExists: true,
    emailValidated: true,
  },
  {
    id: "4",
    name: "Emily Williams",
    company: "Renewable Power Systems",
    email: "emily@renewablepower.com",
    website: "www.renewablepower.com",
    phone: "+34 915 678 901",
    position: "Technical Director",
    location: "Sevilla, España",
    industry: "Power Systems",
    employees: "75-150",
    revenue: "€3M-7M",
    source: "www.renewableenergy.com",
    confidence: 90,
    lastActivity: "2024-01-23T14:20:00Z",
    notes: "Sistemas de energía renovable para industria",
    hasWebsite: true,
    websiteExists: true,
    emailValidated: false,
  },
  {
    id: "5",
    name: "Michael Brown",
    company: "SunPower Installations",
    email: "michael@sunpower-install.com",
    website: "www.sunpower-install.com",
    phone: "+34 916 789 012",
    position: "Sales Manager",
    location: "Bilbao, España",
    industry: "Solar Installation",
    employees: "30-75",
    revenue: "€1.5M-3M",
    source: "www.solarinstallers.com",
    confidence: 85,
    lastActivity: "2024-01-22T11:30:00Z",
    notes: "Instalaciones solares para sector residencial",
    hasWebsite: true,
    websiteExists: false,
    emailValidated: true,
  },
  {
    id: "6",
    name: "Sarah Miller",
    company: "Clean Energy Partners",
    email: "sarah@cleanenergypartners.net",
    website: "www.cleanenergypartners.net",
    phone: "+34 917 890 123",
    position: "Business Development",
    location: "Zaragoza, España",
    industry: "Energy Consulting",
    employees: "20-40",
    revenue: "€800K-1.5M",
    source: "www.greenenergyfirms.net",
    confidence: 87,
    lastActivity: "2024-01-21T16:45:00Z",
    notes: "Consultoría en transición energética",
    hasWebsite: true,
    websiteExists: true,
    emailValidated: true,
  },
  {
    id: "7",
    name: "David Wilson",
    company: "Sustainable Solutions LLC",
    email: "david@sustainablesolutions.co",
    website: "www.sustainablesolutions.co",
    phone: "+34 918 901 234",
    position: "Project Manager",
    location: "Málaga, España",
    industry: "Sustainability",
    employees: "15-30",
    revenue: "€500K-1M",
    source: "www.sustainablesolutions.co",
    confidence: 93,
    lastActivity: "2024-01-20T08:30:00Z",
    notes: "Soluciones sostenibles para empresas",
    hasWebsite: true,
    websiteExists: true,
    emailValidated: true,
  },
  {
    id: "8",
    name: "Lisa Taylor",
    company: "EcoConsult Group",
    email: "lisa@ecoconsult.org",
    website: "www.ecoconsult.org",
    phone: "+34 919 012 345",
    position: "Senior Consultant",
    location: "Murcia, España",
    industry: "Environmental Consulting",
    employees: "40-80",
    revenue: "€2M-4M",
    source: "www.eco-consultants.org",
    confidence: 89,
    lastActivity: "2024-01-19T13:15:00Z",
    notes: "Consultoría ambiental y certificaciones",
    hasWebsite: false,
    websiteExists: false,
    emailValidated: false,
  },
]

export const mockSearchHistory = [
  {
    id: "1",
    date: "2023-04-15T14:30:00Z",
    websites: ["www.solarinstallers.com", "www.greenenergyfirms.net"],
    clientType: "industrial",
    leadsFound: 24,
    leadsContacted: 18,
    status: "completed",
  },
  {
    id: "2",
    date: "2023-04-10T09:15:00Z",
    websites: ["www.eco-consultants.org"],
    clientType: "solar",
    leadsFound: 12,
    leadsContacted: 10,
    status: "completed",
  },
  {
    id: "3",
    date: "2023-04-05T16:45:00Z",
    websites: ["www.renewableenergy.com", "www.sustainablesolutions.co"],
    clientType: "energy",
    leadsFound: 31,
    leadsContacted: 25,
    status: "completed",
  },
  {
    id: "4",
    date: "2023-03-28T11:20:00Z",
    websites: ["www.greenenergyfirms.net"],
    clientType: "residential",
    leadsFound: 18,
    leadsContacted: 15,
    status: "completed",
  },
  {
    id: "5",
    date: "2023-03-20T13:10:00Z",
    websites: ["www.solarinstallers.com", "www.eco-consultants.org"],
    clientType: "commercial",
    leadsFound: 27,
    leadsContacted: 20,
    status: "completed",
  },
]

export const mockEmailCampaigns = [
  {
    id: "1",
    date: "2023-04-15T15:45:00Z",
    subject: "Innovative Solutions for Industrial Energy Efficiency",
    recipients: 18,
    openRate: 72,
    clickRate: 38,
    status: "sent",
  },
  {
    id: "2",
    date: "2023-04-10T10:30:00Z",
    subject: "Partnership Opportunity for Solar Installers",
    recipients: 10,
    openRate: 80,
    clickRate: 50,
    status: "sent",
  },
  {
    id: "3",
    date: "2023-04-05T17:30:00Z",
    subject: "Exclusive Offer for Energy Consultants",
    recipients: 25,
    openRate: 68,
    clickRate: 32,
    status: "sent",
  },
  {
    id: "4",
    date: "2023-03-28T12:15:00Z",
    subject: "New Solutions for Residential Contractors",
    recipients: 15,
    openRate: 73,
    clickRate: 40,
    status: "sent",
  },
  {
    id: "5",
    date: "2023-03-20T14:00:00Z",
    subject: "Commercial Property Energy Optimization",
    recipients: 20,
    openRate: 65,
    clickRate: 35,
    status: "sent",
  },
]
